[package]
name = "nekton"
version = "0.1.0"
authors = ["Simon Dickson <simonhdickson@users.noreply.github.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
failure = "0.1"
futures = { version = "0.1", optional = true }
log = "0.4"
rdkafka = { version = "0.21", optional = true }
rdkafka-sys = { version = "1.0", optional = true }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
typetag = "0.1"

[features]
default = ["kafka"]
kafka = ["futures", "rdkafka", "rdkafka-sys"]
