input:
  type: KafkaIn
  topics: ["test-topic"]
  config:
    group.id: test-consumer
    bootstrap.servers: "localhost:9092"
    session.timeout.ms: 6000
    auto.offset.reset: earliest
pipeline:
  processors:
    - type: Noop
output:
  type: StdOut
